export const CLIENT_LIBRARIES = [
  {
    language: 'JavaScript',
    officialSupport: true,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/javascript/installing',
    gitUrl: 'https://github.com/supabase/supabase-js',
  },
  {
    language: 'Flutter',
    officialSupport: true,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/dart/installing',
    gitUrl: 'https://github.com/supabase/supabase-flutter',
  },
  {
    language: 'Python',
    officialSupport: true,
    releaseState: 'Alpha',
    docsUrl: 'https://supabase.com/docs/reference/python/initializing',
    gitUrl: 'https://github.com/supabase/supabase-py',
  },
  {
    language: 'C#',
    officialSupport: false,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/csharp/installing',
    gitUrl: 'https://github.com/supabase-community/supabase-csharp',
    altIconName: 'c-sharp',
  },
  {
    language: 'Swift',
    officialSupport: true,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/swift/initializing',
    gitUrl: 'https://github.com/supabase/supabase-swift',
  },
  {
    language: 'Kotlin',
    officialSupport: false,
    releaseState: undefined,
    docsUrl: 'https://supabase.com/docs/reference/kotlin/installing',
    gitUrl: 'https://github.com/supabase-community/supabase-kt',
  },
]

export const EXAMPLE_PROJECTS = [
  {
    framework: 'Svelte',
    title: 'Svelte 看板系统',
    description: '一个使用 Supabase 作为存储系统的 Trello 克隆。',
    url: 'https://github.com/joshnuss/supabase-kanban',
    type: 'app',
  },
  {
    framework: 'nextjs',
    title: 'Next.js 实时聊天应用',
    description: '使用 Supabase 实时通信的 Next.js Slack 克隆应用。',
    url: 'https://github.com/supabase/supabase/tree/master/examples/slack-clone/nextjs-slack-clone',
    type: 'app',
  },
  {
    framework: 'nextjs',
    title: 'Next.js 订阅和认证',
    description: '高性能 SaaS 应用程序的一站式入门套件。',
    url: 'https://github.com/nextjs/saas-starter',
    type: 'app',
  },
  {
    framework: 'Expo',
    title: 'Expo 入门模板',
    description: '带有认证流程的底部标签模板。（TypeScript）',
    url: 'https://github.com/codingki/react-native-expo-template/tree/master/template-typescript-bottom-tabs-supabase-auth-flow',
    type: 'mobile',
  },
  {
    framework: 'NestJS',
    title: 'NestJS示例',
    description: '使用 Supabase 认证的 NestJS 示例。',
    url: 'https://github.com/hiro1107/nestjs-supabase-auth',
    type: 'app',
  },
  {
    framework: 'React',
    title: 'React 实时聊天应用',
    description: '使用 Supabase 实时 API 的实时聊天示例应用。',
    url: 'https://github.com/shwosner/realtime-chat-supabase-react',
    type: 'app',
  },
  {
    framework: 'nextjs',
    title: 'Next.js 待办事项应用',
    description: 'Next.js 待办事项列表示例。',
    url: 'https://github.com/supabase/supabase/tree/master/examples/todo-list/nextjs-todo-list',
    type: 'app',
  },
  {
    framework: 'Svelte',
    title: 'Svelte 待办事项应用',
    description: 'Svelte 待办事项应用，使用 TailwindCSS 和 Snowpack。',
    url: 'https://github.com/supabase/supabase/tree/master/examples/todo-list/sveltejs-todo-list',
    type: 'app',
  },
  {
    framework: 'Flutter',
    title: 'Flutter 聊天应用',
    description: '一个使用 supabase-flutter 构建的 Flutter 聊天应用',
    url: 'https://github.com/supabase-community/flutter-chat',
    type: 'mobile',
  },
  {
    framework: 'Swift',
    title: 'Swift 用户管理应用',
    description: '一个使用 supabase-swift 构建的 Swift 用户管理应用',
    url: 'https://github.com/supabase/supabase-swift/tree/main/Examples/UserManagement',
    type: 'mobile',
  },
  {
    framework: 'Swift',
    title: 'Swift Slack 克隆',
    description: '一个使用 supabase-swift 构建的 Swift Slack 克隆应用',
    url: 'https://github.com/supabase/supabase-swift/tree/main/Examples/SlackClone',
    type: 'mobile',
  },
  {
    framework: 'Flutter',
    title: 'Flutter 多因素认证（MFA）应用',
    description: '一个 Flutter 应用，用来演示如何实现多因素认证（MFA）。',
    url: 'https://github.com/supabase/supabase/tree/master/examples/auth/flutter-mfa',
  },
  {
    framework: 'NuxtJS',
    title: 'NuxtJS 待办事项应用',
    description: 'NuxtJS 待办事项应用示例。',
    url: 'https://github.com/nuxt-modules/supabase/tree/main/demo',
  },
]
